# Generated by Django 2.1.2 on 2018-11-20 00:53

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('customers', '0002_auto_20181120_0039'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customer',
            name='customer_zip',
            field=models.CharField(max_length=5, validators=[django.core.validators.RegexValidator('^\\d{1,10}$')]),
        ),
    ]
