# Generated by Django 2.1.2 on 2018-11-20 01:18

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('customers', '0004_auto_20181120_0056'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customer',
            name='state',
            field=models.CharField(max_length=2, validators=[django.core.validators.RegexValidator('.{2}$')]),
        ),
        migrations.AlterField(
            model_name='customer',
            name='zip_Code',
            field=models.CharField(max_length=5, validators=[django.core.validators.RegexValidator('^\\d{5}$')]),
        ),
    ]
