# Generated by Django 2.1.3 on 2018-11-07 03:42

from django.db import migrations


class Migration(migrations.Migration):
    atomic = False
    dependencies = [
        ('orders', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Question',
            new_name='OrderForm',
        ),
    ]
