# Generated by Django 2.1.2 on 2018-12-01 05:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='ProductForm',
        ),
    ]
