# Generated by Django 2.1.2 on 2018-11-30 22:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='choice',
            name='question',
        ),
        migrations.RenameField(
            model_name='orderform',
            old_name='current_date',
            new_name='date_created',
        ),
        migrations.AddField(
            model_name='orderform',
            name='date_updated',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.DeleteModel(
            name='Choice',
        ),
    ]
