# Generated by Django 2.1.2 on 2018-12-01 05:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0003_auto_20181201_0522'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='orderform',
            name='product_id',
        ),
    ]
