# Generated by Django 2.1.2 on 2018-12-01 07:05

from django.db import migrations, models
import orders.validators


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0004_remove_orderform_product_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='orderform',
            name='quantity',
            field=models.IntegerField(default=0, validators=[orders.validators.validate_quantity]),
        ),
    ]
